slam_toolbox:
  ros__parameters:
    use_sim_time: false
    map_frame: map
    odom_frame: odom
    base_frame: base_link
    scan_topic: /scan
    
    # SLAM behavior tuning
    resolution: 0.1
    use_scan_matching: true
    minimum_travel_distance: 0.2
    minimum_travel_heading: 0.1
    max_laser_range: 4.0
    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 4.0
    link_match_minimum_response_fine: 0.1
    loop_search_maximum_distance: 3.0
    do_loop_closing: true
    do_relocalization: true
    enable_interactive_mode: false
